use ecommerce;

-- Q1 List all unique cities where customers are located.
SELECT DISTINCT customer_city 
FROM customers;

-- Q2 Count the number of orders placed in 2017.
SELECT COUNT(order_id)FROM orders  WHERE YEAR(order_purchase_timestamp) = 2017;

-- Q3 Find the total sales per category.
SELECT products.product_category, ROUND(SUM(payments.payment_value),2) AS sales
FROM products
JOIN order_items 
ON products.product_id = order_items.product_id
JOIN payments
ON payments.order_id = order_items.order_id
GROUP BY products.product_category;

-- Q4 Calculate the percentage of orders that were paid in installments.
select ((sum(case when payment_installments >= 1 then 1
else 0 end))/count(*))*100 from payments;

-- Q5 Count the number of customers from each state. 
SELECT customer_state, COUNT(customer_id) AS total_customers
FROM customers
GROUP BY customer_state;

-- Q6 Calculate the number of orders per month in 2018.
SELECT 
    MONTHNAME(order_purchase_timestamp) AS month_name,
    COUNT(order_id) AS orders
FROM orders
WHERE YEAR(order_purchase_timestamp) = 2018
GROUP BY 
    MONTH(order_purchase_timestamp),
    MONTHNAME(order_purchase_timestamp)
ORDER BY 
    MONTH(order_purchase_timestamp) ASC;
    
-- Q7 Find the average number of products per order, grouped by customer city.
WITH count_per_orders 
AS
(SELECT orders.order_id, orders.customer_id, COUNT(order_items.order_id) AS order_count
FROM orders 
JOIN order_items
ON orders.order_id = order_items.order_id
GROUP BY orders.order_id, orders.customer_id)

SELECT customers.customer_city, ROUND(AVG(count_per_orders.order_count),2) AS avg_orders
FROM customers 
JOIN count_per_orders
ON customers.customer_id = count_per_orders.customer_id
GROUP BY customers.customer_city;

-- Q8 Calculate the percentage of total revenue contributed by each product category.
SELECT upper(products.product_category) category, 
round((sum(payments.payment_value)/(SELECT sum(payment_value) FROM payments))*100,2) sales_percentage
FROM products 
JOIN order_items 
ON products.product_id = order_items.product_id
JOIN payments 
ON payments.order_id = order_items.order_id
GROUP BY category 
ORDER BY sales_percentage DESC;

-- Q9 Find the total number of products sold and the average price for each product category.
SELECT products.product_category, COUNT(order_items.product_id) AS total_products, 
ROUND(AVG(order_items.price),2) AS avg_price
FROM products
JOIN order_items
ON products.product_id = order_items.product_id
GROUP BY products.product_category;

-- Q10 Calculate the total revenue generated by each seller, and rank them by revenue.
SELECT*, DENSE_Rank() OVER(ORDER BY revenue DESC) AS ranks FROM
(SELECT order_items.seller_id, ROUND(SUM(payments.payment_value),2) AS revenue
FROM order_items
JOIN payments
ON order_items.order_id = payments.order_id
GROUP BY order_items.seller_id) AS a;

-- Q11 Calculate the moving average of order values for each customer over their order history.
SELECT customer_id, order_purchase_timestamp payment,
AVG(payment) OVER(PARTITION BY customer_id ORDER BY order_purchase_timestamp
ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS mov_avg
FROM
(SELECT orders.customer_id, orders.order_purchase_timestamp, 
payments.payment_value AS payment
FROM payments
JOIN orders
ON payments.order_id = orders.order_id) AS b;

-- Q12 Calculate the cumulative sales per month for each year.
SELECT years, months, payment, ROUND(SUM(payment) OVER(ORDER BY years, months),2) AS cumulatitve_sales 
FROM 
(SELECT YEAR(orders.order_purchase_timestamp) AS years,
MONTHNAME(orders.order_purchase_timestamp) As months,
ROUND(SUM(payments.payment_value),2) AS payment
FROM orders 
JOIN payments
ON orders.order_id = payments.order_id
GROUP BY years, months
ORDER BY years) AS a;

-- Q13 Identify the top 3 customers who spent the most money in each year.
SELECT years, customer_id, payment, d_rank
FROM
(SELECT YEAR(orders.order_purchase_timestamp) years,
orders.customer_id,
ROUND(SUM(payments.payment_value),2) payment,
DENSE_RANK() over(PARTITION BY YEAR(orders.order_purchase_timestamp)
ORDER BY SUM(payments.payment_value) DESC) d_rank
FROM orders JOIN payments 
ON payments.order_id = orders.order_id
GROUP BY YEAR(orders.order_purchase_timestamp),
orders.customer_id) AS a
WHERE d_rank <= 3 ;

